### ISSUE TITLE
Fries not working

### ISSUE THREAD

**Issue by ericb160** [Demo4889/qb-burgershot#1]
Everything works for me except the fries. i make the fries it uses the potato but get no fries. i did spawn fries and ate them and they work but can't cook them.

**Comment by Demo4889** [comment]
> Everything works for me except the fries. i make the fries it uses the potato but get no fries. i did spawn fries and ate them and they work but can't cook them.

I'll check into it when I get home but last I tried they worked. I'll keep you posted

**Comment by ericb160** [comment]
Nice :) Thanks

**Comment by Demo4889** [comment]
> Nice :) Thanks

Issue should be fixed. I missed a pair of {}'s during the progressbar function. I also remove the need for the nh scripts and changed everything over to the qb-menu and qb-input
