### ISSUE TITLE
spatula stays in hand

### ISSUE THREAD

**Issue by ericb160** [Demo4889/qb-burgershot#2]
when you get done cooking the burgers the spatula stays in your hand. fries work now  also getting this in f8 
![image](https://user-images.githubusercontent.com/44815788/145325569-1be135ab-47b7-44e0-a718-f86d28ac3a3a.png)

**Comment by Demo4889** [comment]
Spatula is a common issue with any type of Scenario. Fixing the other issue right now and doing some script cleanup
