### ISSUE TITLE
Suggestion to add the closest player to the cashier

### ISSUE THREAD

**Issue by darknight2590** [Demo4889/qb-burgershot#3]
qb-burgershot:bill

There is a problem that you can give an invoice to a player who is not close to you
Suppose that a player's number was added by mistake
There should be a message that the player is not close

**Comment by Demo4889** [comment]
It doesn't work off the closest player. You enter the person's ID number to bill them.

**Comment by darknight2590** [comment]
Yes, I understand that, but I mean to add an additional condition
You can by number
And the player is also close
It is intended that the two conditions coincide
@Demo4889 
`if id and close then`

**Comment by Demo4889** [comment]
I'll look into it later when I get home

The only problem I see with this is that if someone else is closer, it will come back false and make you do it again

**Comment by darknight2590** [comment]
My players have encountered in the server sometimes it gives the wrong numbers enter bills to other people not closest
